export const OPEN_SIGN_UP_POPUP = "OPEN_SIGN_UP_POPUP"; 
export const OPEN_SIGN_IN_POPUP = "OPEN_SIGN_IN_POPUP"; 
export const ClOSE_SIGN_IN_POPUP = "CLOSE_SIGN_IN_POPUP"; 
export const LOGIN_TO_HOMEPAGE = "LOGIN_TO_HOMEPAGE"; 
export const HANDLE_LOG_OUT = "HANDLE_LOG_OUT";
export const SIGN_UP_TO_HOMEPAGE = "SIGN_UP_TO_HOMEPAGE";

